name: Daily X.com Bookmark Scraper (v2)

on:
  schedule:
    - cron: '0 4 * * *'  # 9 AM UTC daily
  workflow_dispatch:  # Allow manual triggering

jobs:
  scrape:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        # Force fetch all history to ensure we get all changes
        fetch-depth: 0
        # Force a fresh clone to avoid any caching issues
        clean: true
        # Ensure we get the latest changes
        fetch-tags: true
        ref: ${{ github.sha }}

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install dependencies
      run: |
        # Print current directory and files for debugging
        echo "=== Current directory and files ==="
        pwd
        ls -la
        
        # Print git information for debugging
        echo "=== Git information ==="
        git status
        git log -n 3 --oneline
        
        # Verify script version and content
        echo "=== Script content (github-actions-scraper.js) ==="
        if [ -f "github-actions-scraper.js" ]; then
            echo "File exists. First 20 lines:"
            head -n 20 github-actions-scraper.js
            
            # Check for specific version string
            if grep -q "Script started - Version 1.5.6" github-actions-scraper.js; then
                echo "✅ Correct script version (1.5.6) found"
            else
                echo "❌ Incorrect script version found. Expected 1.5.6"
                grep -A 2 -B 2 "Script started - Version" github-actions-scraper.js || echo "Version string not found"
                exit 1
            fi
        else
            echo "❌ github-actions-scraper.js not found!"
            exit 1
        fi
        
        # Clear npm cache and reinstall dependencies
        echo "=== Installing dependencies ==="
        npm cache clean --force
        rm -rf node_modules
        rm -f package-lock.json
        npm install
        # Verify installations
        echo "=== Installed packages ==="
        npm list
        
        # Verify puppeteer version
        echo "=== Puppeteer version ==="
        npm list puppeteer
        
        # Verify file contents one more time after installation
        echo "=== Final script verification ==="
        head -n 5 github-actions-scraper.js

    - name: Run scraper
      env:
        X_USERNAME: ${{ secrets.X_USERNAME }}
        X_PASSWORD: ${{ secrets.X_PASSWORD }}
        N8N_WEBHOOK_URL: ${{ secrets.N8N_WEBHOOK_URL }}
        BROWSERLESS_TOKEN: ${{ secrets.BROWSERLESS_TOKEN }}
      run: |
        echo "Starting script execution..."
        node github-actions-scraper.js || (
          echo "Script failed with exit code $?"
          exit 1
        )
        echo "Script completed successfully"
    
    - name: Upload debug artifacts
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: debug-artifacts
        path: |
          *.png
          bookmarks.json
        retention-days: 1
